title: Bowen Chen's Homepage
page-top-title: Bowen Chen
top-section-bg-text: Optoelectronic Information Science and Engineering
home-subtitle: Bowen Chen&ensp;|&ensp;陈泊闻
copyright-text: '&copy; Bowen Chen 2024-2025. All Rights Reserved.'
